/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pdsl_dpx_NaiveTransEnv */

#ifndef _Included_pdsl_dpx_NaiveTransEnv
#define _Included_pdsl_dpx_NaiveTransEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pdsl_dpx_NaiveTransEnv
 * Method:    Initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_NaiveTransEnv_Initialize
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     pdsl_dpx_NaiveTransEnv
 * Method:    TriggerSpillStart
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_NaiveTransEnv_TriggerSpillStart
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     pdsl_dpx_NaiveTransEnv
 * Method:    Spill
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_NaiveTransEnv_Spill
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     pdsl_dpx_NaiveTransEnv
 * Method:    WaitForSpillDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_NaiveTransEnv_WaitForSpillDone
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_NaiveTransEnv
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_NaiveTransEnv_Destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
