/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pdsl_dpx_SD */

#ifndef _Included_pdsl_dpx_SD
#define _Included_pdsl_dpx_SD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pdsl_dpx_SD
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_SD_Start
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_SD
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_SD_Stop
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_SD
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_SD_Destroy
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_SD
 * Method:    ShowRegisteredClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_SD_ShowRegisteredClass
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_SD
 * Method:    Serialize
 * Signature: (Ljava/lang/Object;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_pdsl_dpx_SD_Serialize
  (JNIEnv *, jclass, jobject);

/*
 * Class:     pdsl_dpx_SD
 * Method:    Deserialize
 * Signature: ([BLjava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_pdsl_dpx_SD_Deserialize
  (JNIEnv *, jclass, jbyteArray, jclass);

/*
 * Class:     pdsl_dpx_SD
 * Method:    Register
 * Signature: (Ljava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_SD_Register
  (JNIEnv *, jclass, jobject);

/*
 * Class:     pdsl_dpx_SD
 * Method:    Initialize
 * Signature: (Ljava/util/Map;Lpdsl/dpx/Options;)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_SD_Initialize
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
