/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pdsl_dpx_Serde */

#ifndef _Included_pdsl_dpx_Serde
#define _Included_pdsl_dpx_Serde
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pdsl_dpx_Serde
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_Serde_Destroy
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_Serde
 * Method:    ShowRegisteredClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_Serde_ShowRegisteredClass
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_Serde
 * Method:    Serialize
 * Signature: (JLjava/lang/Object;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_pdsl_dpx_Serde_Serialize
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     pdsl_dpx_Serde
 * Method:    Deserialize
 * Signature: (J[BLjava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_pdsl_dpx_Serde_Deserialize
  (JNIEnv *, jclass, jlong, jbyteArray, jclass);

/*
 * Class:     pdsl_dpx_Serde
 * Method:    Register
 * Signature: (Ljava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_Serde_Register
  (JNIEnv *, jclass, jobject);

/*
 * Class:     pdsl_dpx_Serde
 * Method:    Initialize
 * Signature: (Ljava/util/Map;Lpdsl/dpx/Options;)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_Serde_Initialize
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     pdsl_dpx_Serde
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_pdsl_dpx_Serde_create
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_Serde
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_Serde_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
