/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pdsl_dpx_TransEnv */

#ifndef _Included_pdsl_dpx_TransEnv
#define _Included_pdsl_dpx_TransEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pdsl_dpx_TransEnv
 * Method:    Initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_TransEnv_Initialize
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     pdsl_dpx_TransEnv
 * Method:    TriggerSpillStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_TransEnv_TriggerSpillStart
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_TransEnv
 * Method:    Append
 * Signature: (I[B[BZ)V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_TransEnv_Append
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     pdsl_dpx_TransEnv
 * Method:    WaitForSpillDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_TransEnv_WaitForSpillDone
  (JNIEnv *, jclass);

/*
 * Class:     pdsl_dpx_TransEnv
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pdsl_dpx_TransEnv_Destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
